[project]
name = "robot-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pybricks>=3.6.1",
    "pybricksdev>=2.3.2",
]
